project_name: qcms-dev

# настройки БД
database:
  connections:
    1:
      dsn: mysql://qbbr:qbbr123@localhost/qcms
      charset: utf8
      collate: utf8_unicode_ci
#    2:
#      dsn: pgsql://qbbr:qbbr123@localhost/qcms
#      charset: utf8
#      collate: utf8_unicode_ci
#    3:
#      dsn: sqlite://%DATA%/qcms.db
#      charset: utf8
#      collate: utf8_unicode_ci
#    4:
#      dsn: dblib://qbbr:qbbr@192.168.100.103/qbbr
#      charset: utf8
#      collate: utf8_unicode_ci
  default: 1
  

# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
time_zone: Europe/Moscow

# http://www.i18nguy.com/unicode/language-identifiers.html
language_code: ru_RU

# время жизни сессии в минутах
session_expire_time: 180

# режим откладки
debug: true